# Generated by Django 3.0.5 on 2020-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolesa', '0002_auto_20200426_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
