# Generated by Django 3.2.1 on 2021-05-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Type', max_length=30)),
                ('engineCapacity', models.FloatField(default=0)),
                ('yearOfManufacture', models.IntegerField(default=2020)),
                ('city', models.CharField(default='none', max_length=30)),
                ('status', models.CharField(default='On the run', max_length=30)),
                ('typeOfEngine', models.CharField(default='diesel fuel', max_length=30)),
                ('mileage', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('imageBase', models.ImageField(default='none', upload_to='')),
                ('image1', models.ImageField(default='none', upload_to='')),
                ('image2', models.ImageField(default='none', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trucks', to='auto.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Type', max_length=30)),
                ('producing_country', models.CharField(max_length=30)),
                ('yearOfManufacture', models.IntegerField(default=2020)),
                ('city', models.CharField(default='none', max_length=30)),
                ('status', models.CharField(default='On the run', max_length=30)),
                ('typeOfEngine', models.CharField(default='diesel fuel', max_length=30)),
                ('mileage', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('imageBase', models.ImageField(default='none', upload_to='')),
                ('image1', models.ImageField(default='none', upload_to='')),
                ('image2', models.ImageField(default='none', upload_to='')),
                ('category', models.ForeignKey(default='SpecializedTechnique', on_delete=django.db.models.deletion.CASCADE, related_name='SpecializedTechnique', to='auto.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Mototechnics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Type', max_length=30)),
                ('engineCapacity', models.FloatField(default=0)),
                ('yearOfManufacture', models.IntegerField(default=2020)),
                ('city', models.CharField(default='none', max_length=30)),
                ('status', models.CharField(default='On the run', max_length=30)),
                ('mileage', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('imageBase', models.ImageField(default='none', upload_to='')),
                ('image1', models.ImageField(default='none', upload_to='')),
                ('image2', models.ImageField(default='none', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='sedan', max_length=30)),
                ('transmission', models.CharField(default='Automatic', max_length=30)),
                ('steeringWheel', models.CharField(default='left', max_length=30)),
                ('driveWheel', models.CharField(default='front-wheel drive', max_length=30)),
                ('numberofdoors', models.IntegerField(default=4)),
                ('engineCapacity', models.FloatField(default=2.0)),
                ('vin', models.IntegerField(default=123)),
                ('description', models.CharField(default='', max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('yearOfManufacture', models.IntegerField(default=2020)),
                ('city', models.CharField(default='none', max_length=30)),
                ('status', models.CharField(default='On the run', max_length=30)),
                ('typeOfEngine', models.CharField(default='petrol', max_length=30)),
                ('mileage', models.IntegerField(default=0)),
                ('color', models.CharField(default='white', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('imageBase', models.ImageField(default='none', upload_to='')),
                ('image1', models.ImageField(default='none', upload_to='')),
                ('image2', models.ImageField(default='none', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.manufacturer')),
            ],
        ),
    ]
