# Generated by Django 3.2.1 on 2021-05-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
        ('auto', '0002_auto_20210515_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_.userprofile'),
        ),
        migrations.AddField(
            model_name='specializedtechnique',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_.userprofile'),
        ),
        migrations.AddField(
            model_name='trucks',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_.userprofile'),
        ),
    ]
